name: nakama-node-1
data_dir: "./data/"


logger:
  stdout: true
  level: 'info'
  file: 'D:\Nakama\log\logfile.log'
  rotation: false
  max_size: 100
  max_age: 0
  max_backups: 0
  local_time: false
  compress: false
           
metrics:
  reporting_freq_sec: 60
  namespace: ""
  prometheus_port: 7354

database:
  address:
  - 'postgres:hienduc@localhost:5432/nakama'
  conn_max_lifetime_ms: 0
  max_open_conns: 1000
  max_idle_conns: 1000

runtime:
  env:
  - 'example_apikey=example_apivalue'
  - 'encryptionkey=afefa==e332*u13=971mldq'
  path: 'D:\Nakama\data\modules\'
  http_key: 'defaulthttpkey'

socket:
  server_key: "defaultkey"
  port: 7350
  max_message_size_bytes: 4096 # bytes
  read_timeout_ms: 100000
  write_timeout_ms: 100000
  idle_timeout_ms: 600000
  write_wait_ms: 500000
  pong_wait_ms: 10000
  ping_period_ms: 8000 # Must be less than pong_wait_ms
  outgoing_queue_size: 30

session:
  encryption_key: "defaultencryptionkey"
  token_expiry_sec: 1000
  refresh_encryption_key: "defaultrefreshencryptionkey"
  refresh_token_expiry_sec: 1000
  single_socket: true
  single_match: true

social:
  steam:
  publisher_key: ""
  app_id: 0

console:
  port: 7351
  username: "admin"
  password: "password"

cluster:
  join:
    - "10.0.0.2:7352"
    - "10.0.0.3:7352"
  gossip_bindaddr: "0.0.0.0"
  gossip_bindport: 7352
  rpc_port: 7353
  local_priority: true
  work_factor_interval_ms: 1000

tracker:
  max_delta_sizes:
    - 100
    - 1000
    - 10000

matchmaker:
  max_tickets: 2
  interval_sec: 15
  max_intervals: 3

iap:
  apple:
    shared_password: "password"
  google:
    client_email: "email@google.com"
    private_key: "pk"
  huawei:
    public_key: "pk"
    client_id: "id"
    client_secret: "secret"